version: 0.2
env:
  variables:
    DEBIAN_FRONTEND: noninteractive

phases:
  pre_build:
    commands:
      - find ./ -mtime +10950 -print 
  build:
    commands:
      - pip install awscli==1.11.37
      - npm install
      - node_modules/.bin/babel index.js -o index.js
  post_build:
    commands:
      - find ./ -mtime +10950 -print 
